<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <EmbeddedResource Include="EndLabel\EndLabel.html" />
	  <EmbeddedResource Include="EmptyPage\EmptyPage.html" />
	  <EmbeddedResource Include="StuffingSheet\StuffingSheet.html" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Editor\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>
